version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    user: "0:0"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
  
  kafka-broker:
    image: confluentinc/cp-kafka:latest
    user: "0:0"
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 1 
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true' 
    restart: unless-stopped